<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/resource/jsp/common.jsp"%>
<%@ page import="com.landray.kmss.web.taglib.xform.TagUtils" %>
<table id="fd_3991e0617d1cba"  align="center" class="tb_normal"  layout2col="undefined"  fd_type="standardTable" style="width:100%;"><tbody><tr><td row="0" column="0" class="td_normal_title" width="197.85">
			<label  class="xform_label" line="normal"  fd_type="textLabel" style="display: inline-block; width: auto; word-break: break-all; overflow-wrap: break-word;;word-break:break-all;;word-wrap:break-word;"><xform:lang id='fd_3991e063375fc8' option='content'/></label>
</td><td row="0" column="1" width="461.65">
			<div  class="xform_inputText" canshow="true"  fd_type="inputText" style="display: inline-block; width: 147px; word-break: break-all; overflow-wrap: break-word;"><xformflag flagid='fd_3991e064cfb7f4' id='_xform_extendDataFormInfo.value(fd_3991e064cfb7f4)' property='extendDataFormInfo.value(fd_3991e064cfb7f4)' flagtype='xform_text' _xform_type='text'><xform:xtext property="extendDataFormInfo.value(fd_3991e064cfb7f4)" style="display: inline-block; width: 147px; word-break: break-all; overflow-wrap: break-word;width:120px;" required="false" className="inputsgl xform_inputText" subject="${xform:subject('fd_3991e064cfb7f4','label')}" title="${xform:subject('fd_3991e064cfb7f4','label')}" onValueChange="__xformDispatch" />
</xformflag></div>
</td><td row="0" column="2" class="td_normal_title" width="197.85">
			<label  class="xform_label" line="normal"  fd_type="textLabel" style="display: inline-block; width: auto; word-break: break-all; overflow-wrap: break-word;;word-break:break-all;;word-wrap:break-word;"><xform:lang id='fd_3991e06401e258' option='content'/></label>
</td><td row="0" column="3" width="461.65">
			<div  class="xform_inputText" canshow="true"  fd_type="inputText" style="display: inline-block; width: 147px; word-break: break-all; overflow-wrap: break-word;"><xformflag flagid='fd_3991e065a4dbaa' id='_xform_extendDataFormInfo.value(fd_3991e065a4dbaa)' property='extendDataFormInfo.value(fd_3991e065a4dbaa)' flagtype='xform_text' _xform_type='text'><xform:xtext property="extendDataFormInfo.value(fd_3991e065a4dbaa)" style="display: inline-block; width: 147px; word-break: break-all; overflow-wrap: break-word;width:120px;" required="false" className="inputsgl xform_inputText" subject="${xform:subject('fd_3991e065a4dbaa','label')}" title="${xform:subject('fd_3991e065a4dbaa','label')}" onValueChange="__xformDispatch" />
</xformflag></div>
</td></tr><tr><td row="1" column="0" class="td_normal_title" width="197.85">&nbsp;</td><td row="1" column="1" width="461.65">&nbsp;</td><td row="1" column="2" class="td_normal_title" width="197.85">&nbsp;</td><td row="1" column="3" width="461.65">&nbsp;</td></tr><tr><td row="2" column="0" class="td_normal_title" width="197.85">&nbsp;</td><td row="2" column="1" width="461.65">&nbsp;</td><td row="2" column="2" class="td_normal_title" width="197.85">&nbsp;</td><td row="2" column="3" width="461.65">&nbsp;</td></tr><tr><td row="3" column="0" class="td_normal_title" width="197.85">&nbsp;</td><td row="3" column="1" width="461.65">&nbsp;</td><td row="3" column="2" class="td_normal_title" width="197.85">&nbsp;</td><td row="3" column="3" width="461.65">&nbsp;</td></tr></tbody></table>